export const fortunesArray = [
      "Você não precisa entender o tempo — só caminhar com ele.",
      "O medo grita, mas a sua coragem sempre fala mais alto quando você escuta.",
      "Genialidade não é brilho, é insistência teimosa.",
      "Seja curiosa como o Doutor: perguntas salvam mais do que respostas.",
      "O fracasso é só um planeta de passagem, não seu endereço.",
      "Ninguém descobre nada novo com medo de parecer boba.",
      "Você não veio ao mundo pra repetir padrões — veio pra quebrá-los.",
      "Seu futuro não nasce pronto; nasce do caos que você resolve encarar.",
      "Você pode tropeçar na dúvida, mas é a ação que te levanta.",
      "É melhor errar se movendo do que apodrecer parada.",
      "A vida não te dá manual, mas te dá escolhas — e isso é poder.",
      "Você é mais forte do que sua pior lembrança.",
      "Não espere o universo te entender; faça ele te notar.",
      "Quando tudo parecer perdido, mude a perspectiva, não o sonho.",
      "Ser gentil consigo mesma é a revolução mais silenciosa e mais forte.",
      "O mundo só muda quando alguém decide que já deu.",
      "Ninguém programa um grande sistema sem bug — a vida é igual.",
      "Seja teimosa com seus sonhos, mas flexível com o caminho.",
      "Coragem é continuar mesmo tremendo.",
      "Você não precisa de aprovação, precisa de movimento.",
      "A disciplina te abraça quando a motivação foge.",
      "Seu brilho incomoda quem vive no escuro — não se apague por isso.",
      "Você não é sua ansiedade; você é quem enfrenta ela todo dia.",
      "Aprender é mais valioso que parecer perfeita.",
      "Os limites que você rompe hoje viram liberdade amanhã.",
      "Persista até que sua própria versão duvide se ainda é você — e sorria.",
      "Quem duvida de você não merece assistir sua vitória.",
      "Ninguém vira mestre sem passar pela fase de iniciante.",
      "Há força nos seus silêncios, mas não se esconda neles.",
      "Tudo muda quando você decide que não aceita menos que respeito.",
      "Você não precisa saber tudo; só precisa querer aprender mais.",
      "Às vezes a vida quebra você só pra abrir espaço pro novo.",
      "Você não está atrasada — você está amadurecendo.",
      "O futuro é só um código que você ainda não escreveu.",
      "Você pode ser mágica e lógica ao mesmo tempo.",
      "Quando duvidar de si, relembre o que você já sobreviveu.",
      "Você não precisa ser gigante, só precisa continuar crescendo.",
      "A vida não é sobre ser perfeita; é sobre ser verdadeira.",
      "Seus passos pequenos ainda são passos.",
      "A paz chega quando você para de disputar com quem não corre com você.",
      "Sua mente é sua melhor ferramenta — afie, não negligencie.",
      "Você não tem que aguentar tudo — tem que escolher o que vale a pena.",
      "Coragem não é ausência de medo; é ação apesar dele.",
      "O mundo tenta te moldar, mas você nasceu pra criar forma própria.",
      "Os dias ruins não anulam seus dias brilhantes.",
      "A dúvida só vence se você parar.",
      "O universo gosta de quem tenta de novo.",
      "Seja humilde pra aprender e ousada pra aplicar.",
      "Pensar grande assusta, mas pensar pequeno sufoca.",
      "O caos é só o começo da criação.",
      "Não venda barato sua paz.",
      "Você merece descanso, mas não merece desistência.",
      "Quem constrói aos poucos constrói firme.",
      "A vida muda quando você decide viver por si, não pelos outros.",
      "Seja a versão que você teria orgulho de encontrar no futuro.",
      "Não tenha medo de recomeçar — às vezes você só precisa mudar o roteiro.",
      "Você não precisa correr, precisa avançar.",
      "Quando sentir que perdeu o controle, lembre que ainda tem escolha.",
      "A verdade liberta, mesmo que arranhe.",
      "Você não tem obrigação de sustentar peso de ninguém.",
      "O mundo abre portas para quem gira maçanetas sem permissão.",
      "Seja curiosa demais para ser limitada.",
      "Suas falhas são degraus, não prisões.",
      "Você não precisa provar nada pra ninguém, só pra si mesma.",
      "Não permita que a opinião alheia codifique sua vida.",
      "Seja mais paciente com seu processo.",
      "O impossível só existe até alguém fazer.",
      "Seus sonhos não são exagerados; seu medo é que é barulhento.",
      "Você é mais criativa do que acredita — confie nas suas ideias.",
      "Não pare na metade — o final pode ser lindo.",
      "A vida te testa, mas também te recompensa.",
      "Você não precisa ter luz própria o tempo todo — só não apague de vez.",
      "Seus limites podem ser expandidos como qualquer universo.",
      "Sim, é difícil — mas você também é.",
      "Você não precisa de sorte, precisa de coragem pra continuar.",
      "Seja seletiva com sua energia; ela vale ouro.",
      "Você é a protagonista da sua história, não a figurante.",
      "O passado ensina, mas não manda em você.",
      "Quem pensa demais trava — quem age aprende.",
      "Você está exatamente onde precisava estar pra dar o próximo passo.",
      "A vida sempre recompensa quem insiste quando ninguém está olhando.",
      "Você é capaz de mais do que imagina quando finalmente tenta.",
      "Não se perca tentando caber nos outros.",
      "O amanhã nasce da coragem de hoje.",
      "Sua intuição é uma bússola — siga sem medo.",
      "Não aceite menos do que a sua paz exige.",
      "A dúvida paralisa; a ação liberta.",
      "Você não precisa explicar seus sonhos pra quem não sonha.",
      "Você tem força demais pra viver pequena.",
      "Continue — o caminho ainda não mostrou o melhor que tem.",
      "Quem olha para as estrelas não pode viver rastejando.",
      "Evoluir dói, mas ficar estagnada dói muito mais.",
      "Você tem o direito de começar de novo quantas vezes quiser.",
      "Confie no processo, mesmo quando ele parece um labirinto.",
      "A vida sempre guarda uma virada pra quem não abandona o jogo.",
      "Você é movimento, não estagnação.",
      "Seu medo não manda em você — só fala alto.",
      "E mesmo quando tudo desmorona, você sempre reconstrói."
    ];