export const fortunesArray = [
      "Você precisa parar de esperar o momento perfeito — ele não existe.",
      "Nem todo mundo que anda com você torce por você.",
      "Seus hábitos de hoje estão moldando a vida que você vai reclamar amanhã.",
      "Você já deixou de avançar mais vezes por medo do que por falta de capacidade.",
      "Ninguém vai te salvar — mas você consegue se levantar.",
      "A vida não é justa, mas você pode ser mais esperta que ela.",
      "Pare de pedir permissão para viver do seu jeito.",
      "O mundo não vai desacelerar só porque você cansou.",
      "O que você evita agora volta maior depois.",
      "Você precisa aprender a se escolher sem culpa.",
      "Às vezes o caminho certo dói mais que o errado — mas cura.",
      "Não confunda conforto com felicidade.",
      "Você não precisa vencer hoje, só não pode desistir.",
      "Seus sonhos só funcionam se você fizer sua parte.",
      "Nem tudo que te machuca é inimigo; às vezes é lição.",
      "Você não precisa ser forte o tempo todo — só precisa continuar.",
      "Às vezes o que você quer não é o que você precisa.",
      "O universo não te deve nada, mas te oferece tudo se você se mover.",
      "Pare de romantizar quem não move um dedo por você.",
      "Nem todo silêncio é paz — às vezes é engolir sentimento demais.",
      "Seus limites estão pedindo atenção faz tempo.",
      "O que você tolera diz muito sobre como você se enxerga.",
      "A vida te testa exatamente onde você costuma tropeçar.",
      "Se você não mudar, nada muda.",
      "Você sabe a resposta; só tem medo de admitir.",
      "O passado não te define, mas te cobra quando você não aprende.",
      "Você precisa descansar, não desistir.",
      "Nem todo mundo merece a versão mais bonita de você.",
      "Sua intuição já te avisou — confie mais nela.",
      "Pedir ajuda não te faz fraca — te faz humana.",
      "A cura é lenta, mas chega.",
      "Você já sobreviveu a coisas que achou que não conseguiria.",
      "Não subestime o poder de um começo pequeno.",
      "Você pode falhar mil vezes e ainda assim tentar outra vez.",
      "O amor que você procura começa no espelho.",
      "Guarde energia para o que realmente importa.",
      "Seu futuro agradece quando você diz 'não' hoje.",
      "Às vezes perder alguém é ganhar paz.",
      "O esforço que você faz agora vai ecoar daqui a anos.",
      "Quem realmente te quer bem não te diminui.",
      "Você não está atrasada, está no seu ritmo.",
      "Cuidar de si mesma não é luxo — é sobrevivência.",
      "A vida melhora quando você para de se sabotar.",
      "Seja honesta consigo mesma, mesmo que doa.",
      "Você precisa parar de esperar que os outros façam por você.",
      "Nem tudo acontece do jeito que você quer — mas acontece do jeito que você precisa.",
      "Você merece coisas simples e boas, mesmo nos dias ruins.",
      "Alguém vai enxergar seu valor — mas você precisa enxergar antes.",
      "O recomeço parece caos no início, mas vira luz depois.",
      "Você está aprendendo, e isso já é vitória."
    ];